# Generated by Django 4.2.5 on 2023-09-12 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_posts_id'),
    ]

    operations = [
    ]
