# Generated by Django 4.2.5 on 2023-09-13 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20230912_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
