# Generated by Django 4.2.5 on 2023-09-14 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_posts_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='title',
            field=models.CharField(help_text='Titre du poste', max_length=200),
        ),
    ]
