# Generated by Django 4.2.5 on 2023-09-14 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_posts_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='imagen_posts',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
