# Generated by Django 4.2.5 on 2023-09-14 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_posts_description_alter_posts_imagen_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
