# Generated by Django 4.2.5 on 2023-09-15 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_posts_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='rating',
        ),
    ]
