# Generated by Django 4.2.5 on 2023-09-19 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_rating_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='post',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='user',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='comments',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
