# Generated by Django 4.2.5 on 2023-09-21 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_category_remove_posts_categoria_delete_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='imagen_posts',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
