# Generated by Django 4.2.5 on 2023-09-21 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_alter_posts_imagen_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='imagen_posts',
            field=models.ImageField(blank=True, null=True, upload_to='static/image/'),
        ),
    ]
