# Generated by Django 4.2.5 on 2023-09-21 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_alter_posts_imagen_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
