# Generated by Django 4.2.5 on 2023-09-21 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_remove_posts_category_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='imagen_posts',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
