# Generated by Django 4.2.5 on 2023-09-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_alter_posts_imagen_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='categorie',
            field=models.CharField(choices=[('restaurant', 'Restaurant'), ('bar', 'Bar'), ('tourisme', 'Tourisme')], default='restaurant', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='posts',
            name='imagen_posts',
            field=models.ImageField(blank=True, default='default_image.png', null=True, upload_to=''),
        ),
    ]
