# Generated by Django 4.2.5 on 2023-09-29 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0024_userprofile_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='user_icon.jpeg', null=True, upload_to='profile_picture'),
        ),
    ]
