# Generated by Django 4.2.5 on 2023-10-03 15:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0026_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
