# Generated by Django 4.2.5 on 2023-10-03 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0028_remove_posts_uuid_posts_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='hauteur_image',
            field=models.PositiveIntegerField(default=600),
        ),
        migrations.AddField(
            model_name='posts',
            name='largeur_image',
            field=models.PositiveIntegerField(default=800),
        ),
    ]
