# Generated by Django 4.2.5 on 2023-10-03 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0032_alter_posts_hauteur_image_alter_posts_largeur_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='hauteur_image',
            field=models.PositiveIntegerField(default=350),
        ),
        migrations.AlterField(
            model_name='posts',
            name='largeur_image',
            field=models.PositiveIntegerField(default=450),
        ),
    ]
