# Generated by Django 4.2.5 on 2023-10-04 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0034_comment_parent_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='comments',
            field=models.ManyToManyField(related_name='post_comments', to='posts.comment'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='categorie',
            field=models.CharField(choices=[('restaurant', 'Restaurant'), ('bar', 'Bar'), ('tourisme', 'Tourisme'), ('night clubs', 'Night clubs')], max_length=20),
        ),
    ]
