# Generated by Django 4.2.5 on 2023-10-06 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0035_posts_comments_alter_posts_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_posts', to='posts.userprofile'),
        ),
    ]
