# Generated by Django 4.2.5 on 2023-10-11 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0036_posts_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
