# Generated by Django 4.2.5 on 2023-10-13 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0037_subscription_first_name_subscription_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
