# Generated by Django 4.2.5 on 2023-10-13 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0038_posts_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='num_ratings',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
