# Generated by Django 4.2.5 on 2023-10-13 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0039_posts_num_ratings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='num_ratings',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='rating',
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.posts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='posts',
            name='ratings',
            field=models.ManyToManyField(related_name='post_rating', through='posts.Rating', to=settings.AUTH_USER_MODEL),
        ),
    ]
