# Generated by Django 4.2.5 on 2023-10-13 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0040_remove_posts_num_ratings_remove_posts_rating_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='created_at',
        ),
    ]
