# Generated by Django 4.2.5 on 2023-10-15 21:29

from django.db import migrations

from posts import models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0043_alter_rating_rating'),

    ]

    operations = [

    ]
