# Generated by Django 4.2.5 on 2023-10-15 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0044_auto_20231015_2129'),
    ]

    operations = [
    ]
