# Generated by Django 4.2.5 on 2023-10-16 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0046_alter_posts_description_alter_posts_subtitle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='first_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='last_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
