# Generated by Django 4.2.5 on 2023-10-16 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0048_alter_userprofile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
