# Generated by Django 4.2.5 on 2023-10-18 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0049_posts_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='categorie',
            field=models.CharField(choices=[('restaurant', 'Restaurant'), ('bar', 'Bar'), ('tourisme', 'Tourisme'), ('night_clubs', 'Night clubs')], max_length=20),
        ),
    ]
