# Generated by Django 4.2.5 on 2023-10-18 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0050_alter_posts_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='categorie',
            field=models.CharField(choices=[('restaurant', 'Restaurant'), ('bar', 'Bar'), ('tourisme', 'Tourisme'), ('nightClubs', 'Night clubs')], max_length=20),
        ),
    ]
