# Generated by Django 4.2.5 on 2023-10-19 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0052_posts_keywords_posts_meta_description_posts_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
