# Generated by Django 4.2.5 on 2023-10-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0054_alter_posts_user_profile_delete_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='hauteur_image',
            new_name='image_height',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='largeur_image',
        ),
        migrations.AddField(
            model_name='posts',
            name='image_width',
            field=models.PositiveIntegerField(default=400),
        ),
    ]
