# Generated by Django 4.2.5 on 2023-10-19 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0055_rename_hauteur_image_posts_image_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='image_height',
            field=models.PositiveIntegerField(default=400),
        ),
        migrations.AlterField(
            model_name='posts',
            name='image_width',
            field=models.PositiveIntegerField(default=350),
        ),
    ]
