# Generated by Django 4.2.5 on 2023-11-07 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0062_alter_posts_image_height_alter_posts_image_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='imagen_posts',
            field=models.ImageField(default='default_image.png', upload_to=''),
        ),
    ]
