# Generated by Django 4.2.7 on 2023-11-07 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0064_alter_posts_imagen_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='imagen_posts',
            field=models.ImageField(default='default_image.png', upload_to=''),
        ),
    ]
