# Generated by Django 3.2.10 on 2023-11-17 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_userprofile_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='post_count',
        ),
    ]
