# Generated by Django 3.2.10 on 2023-11-17 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_remove_userprofile_post_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='post_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
